#pragma once

#define CUBE_VERTEX_GEN_CALLABLE 1
#define EDGES_VAO_INIT_CALLABLE 2
#define FACES_VAO_INIT_CALLABLE 3
#define FACE_VAO_INIT_CALLABLE 4
#define FETCHED_SURFACE_VERTEX_GEN_CALLABLE 5
#define MESH_OUTLINER_ADDER_CALLABLE 6
#define MESH_VAO_INIT_CALLABLE 7
#define PLANE_VERTEX_GEN_CALLABLE 8
#define SCENE_FACES_ADDER_CALLABLE 9
#define SCENE_MESH_ADDER_CALLABLE 10