#pragma once

enum CallableIDS {
    CUBE_VERTEX_GEN_CALLABLE = 1,
    EDGES_VAO_INIT_CALLABLE,
    FACES_VAO_INIT_CALLABLE,
    FACE_VAO_INIT_CALLABLE,
    FETCHED_SURFACE_VERTEX_GEN_CALLABLE,
    MESH_OUTLINER_ADDER_CALLABLE,
    MESH_VAO_INIT_CALLABLE,
    PLANE_VERTEX_GEN_CALLABLE,
    SCENE_FACES_ADDER_CALLABLE,
    SCENE_MESH_ADDER_CALLABLE
};
