site_name: SurfaceEditor Docs

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    # - navigation.tabs     # disabled to use side nav instead
    # - navigation.top      # disabled to use side nav instead
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Src:
      - Ray: Ray.md
      - Ray2D: Ray2D.md
      - ViewPortsController: ViewPortsController.md
      - Core:
          - Application: Application.md
          - Event: Event.md
          - Input: Input.md
          - Layer: Layer.md
          - Window: Window.md
          - EditorSettings: EditorSettings.md
      - Callables:
          - Callable: Callable.md
          - FunctionComposer: FunctionComposer.md
      - Callabacks:
          - Callback: Callback.md
      - Structures:
          - HalfEdge: HalfEdge.md
          - Octree: Octree.md
          - QuadTree: QuadTree.md
      - Editing:
            - Selection:
              - FaceSelectionManager: FaceSelectionManager.md
              - MeshSelectionManager: MeshSelectionManager.md
              - SelectionController: SelectionController.md
              - SelectionHolder: SelectionHolder.md
      - IO:
          - CurlFileFetcher: CurlFileFetcher.md
          - OBJExporter: OBJExporter.md
          - OBJImporter: OBJImporter.md
          - TiffGrayscaleMapLoader: TiffGrayscaleMapLoader.md
      - Params:
          - OperationParams: OperationParams.md
      - Patterns:
          - Command: Command.md
          - Observer: Observer.md
      - Primitives:
          - AABB: AABB.md
          - BoundingRegion2D: BoundingRegion2D.md
          - Plane: Plane.md
          - Sphere: Sphere.md
      - Renderer:
          - Buffers: Buffers.md
          - Material: Material.md
          - Renderer: Renderer.md
          - Shader: Shader.md
      - Scene:
          - Camera: Camera.md
          - Mesh: Mesh.md
          - Scene: Scene.md
          - ViewPortLayerRenderSettings: ViewPortLayerRenderSettings.md
      - Tools:
          - BrushInteractionHandler: BrushInteractionHandler.md
          - BrushTool: BrushTool.md
          - DeselectionHandler: DeselectionHandler.md
          - FaceDeselectionTool: FaceDeselectionTool.md
          - FaceSelectionTool: FaceSelectionTool.md
          - InteractionHandler: InteractionHandler.md
          - MeshSelectionTool: MeshSelectionTool.md
          - SelectionHandler: SelectionHandler.md
          - Tool: Tool.md
          - ToolRegistry: ToolRegistry.md
      - Utils:
          - ContainerUtils: ContainerUtils.md
          - GeometryUtils: GeometryUtils.md
          - glm_overrides: glm_overrides.md
          - InterpolationUtils: InterpolationUtils.md
          - ThirdApiUtils: ThirdApiUtils.md
          
          
            
