#pragma once

enum LayerIDS {
    ADDITION_LAYER = 0,
    GIZMO_LAYER,
    IM_GUI_LAYER,
    IMPORT_EXPORT_LAYER,
    MODIFIERS_LAYER,
    OUTLINER_LAYER,
    PRINTABLE_MESH_SETTINGS_POP_UP_LAYER,
    REMOVAL_LAYER,
    SCULPT_TOOLS_LAYER,
    SELECTION_LAYER,
    DEBUG_LAYER,
    OBJECT_MANIPULATION_LAYER,
    OBJECTS
};
