#pragma once

#define ADDITION_LAYER 0
#define GIZMO_LAYER 1
#define IM_GUI_LAYER 2
#define IMPORT_EXPORT_LAYER 3
#define MODIFIERS_LAYER 4
#define OUTLINER_LAYER 5
#define PRINTABLE_MESH_SETTINGS_POP_UP_LAYER 6
#define REMOVAL_LAYER 7
#define SCULPT_TOOLS_LAYER 8
#define SELECTION_LAYER 9