package "OutlinerLayerPlugin"
{
    class OutlinerLayer
}
OutlinerLayerPlugin --> LayerIDs
OutlinerLayerPlugin --> PluginAPI
    PluginAPI --> CallbackRegister
        CallbackRegister --> Callback
            Callback --> FunctionComposer
                FunctionComposer --> CallableRegistry
                    CallableRegistry --> Callable
                        Callable --> Command
    PluginAPI --> CommandRegistry
        CommandRegistry --> Command
            Command --> OperationalParams
                OperationalParams --> Scene
                    Scene --> Mesh
                        Mesh --> Material
                            Material --> glm
                            Material --> Shader
                                Shader --> glm
                                Shader --> glad
                        Mesh --> ExtendedHalfEdge
                            ExtendedHalfEdge --> HalfEdge
                            ExtendedHalfEdge --> ContainerUtils
                        Mesh --> BufferLayouts
                            BufferLayouts --> Material
                            BufferLayouts --> BufferStorages
                                BufferStorages --> BufferStorageData
                                    BufferStorageData --> Buffers
                                    BufferStorageData --> glm
                                BufferStorages --> Buffers
                                    Buffers --> glad
                        Mesh --> AABB                            
                        Mesh --> glm
                    Scene --> AABB
                        AABB --> Ray
                            Ray --> Ray2D
                                Ray2D --> glm
                            Ray --> Sphere
                            Ray --> Camera
                            Ray --> Window
                            Ray --> glm
                        AABB --> Plane
                            Plane --> glm
                        AABB --> Sphere
                            Sphere --> glm
                        AABB --> glm
                    Scene --> Camera
                        Camera --> glm
                    Scene --> Octree
                        Octree --> AABB
                    Scene --> Window
                        Window --> Event
                        Window --> Camera
                        Window --> glad
                        Window --> glfw3
                    Scene --> PrintableMesh
                        PrintableMesh --> QuadTree
                            QuadTree --> BoundingRegion2D
                            QuadTree --> AABB
                        PrintableMesh --> BoundingRegion2D
                            BoundingRegion2D --> glm
                            BoundingRegion2D --> Ray2D
                        PrintableMesh --> GeometryUtils
                            GeometryUtils --> Plane
                            GeometryUtils --> ExtendedHalfEdge
                            GeometryUtils --> glm
                        PrintableMesh --> Plane
                        PrintableMesh --> ContainerUtils
                        PrintableMesh --> Ray2D
                        PrintableMesh --> Mesh
                        PrintableMesh --> BufferLayouts
                        PrintableMesh --> ExtendedHalfEdge
                        PrintableMesh --> glm
                OperationalParams --> ImGuizmo
    PluginAPI --> LayerRegistry
        LayerRegistry --> Layer
            Layer --> Event
    PluginAPI --> ToolRegistry
        ToolRegistry --> Tool
            Tool --> InteractionHandler
                InteractionHandler --> Command
    PluginAPI --> Observer
        Observer --> Command
        Observer --> Callback
    PluginAPI --> Application
        Application --> Window
        Application --> Layer
        Application --> ImGuiLayer
            ImGuiLayer --> Layer
            ImGuiLayer --> LayerRegistry
            ImGuiLayer --> LayerIDs
            ImGuiLayer --> Application
            ImGuiLayer --> glfw3
            ImGuiLayer --> imgui
    PluginAPI --> WindowLayerBus
OutlinerLayerPlugin --> Observer
OutlinerLayerPlugin --> CommandRegistry
OutlinerLayerPlugin --> Layer
OutlinerLayerPlugin --> WindowLayerBus
OutlinerLayerPlugin --> LayerRegistry
OutlinerLayerPlugin --> LayerIDs

package "AddNodesToOutlinerLayerPlugin"
{
    class AddOutlinerNodeCallBacks
    class MeshOutlinerAdderCallable
}
AddNodesToOutlinerLayerPlugin --> ViewPortsController
    ViewPortsController --> SelectionController
        SelectionController --> MeshSelectionManager
            MeshSelectionManager --> SelectionHolder
                SelectionHolder --> Mesh
            MeshSelectionManager --> Mesh
        SelectionController --> FaceSelectionManager
            FaceSelectionManager --> SelectionHolder
    ViewPortsController --> ViewPortLayerRenderSettings
        ViewPortLayerRenderSettings --> Shader
    ViewPortsController --> Input
        Input --> Application
    ViewPortsController --> Observer
    ViewPortsController --> Tool
AddNodesToOutlinerLayerPlugin --> OutlinerLayer
AddNodesToOutlinerLayerPlugin --> PluginAPI
AddNodesToOutlinerLayerPlugin --> CallbackIDs
AddNodesToOutlinerLayerPlugin --> CommandIDs
AddNodesToOutlinerLayerPlugin --> LayerIDs
AddNodesToOutlinerLayerPlugin --> Observer
AddNodesToOutlinerLayerPlugin --> CallableIDs
AddNodesToOutlinerLayerPlugin --> Callback
AddNodesToOutlinerLayerPlugin --> CommandRegistry
AddNodesToOutlinerLayerPlugin --> OperationalParams

package "MeshAdderCallablesPlugin"{
    class MeshVaoInitCallable
    class SceneMeshAdderCallable
}
MeshAdderCallablesPlugin --> PluginAPI
MeshAdderCallablesPlugin --> MaterialRegistry
    MaterialRegistry --> Material
MeshAdderCallablesPlugin --> CallableIDs
MeshAdderCallablesPlugin --> ViewPortsController
MeshAdderCallablesPlugin --> CallableRegistry
MeshAdderCallablesPlugin --> GeometryUtils
MeshAdderCallablesPlugin --> ExtendedHalfEdge
MeshAdderCallablesPlugin --> BufferStorages
MeshAdderCallablesPlugin --> Callable
MeshAdderCallablesPlugin --> OperationalParams

package "AddCubePlugin" {
    class AddCubeCommand
    class AddCubeCallback
    class CubeVertexGenCallable

    AddCubeCallback --> CubeVertexGenCallable      
}
AddCubePlugin --> MeshAdderCallablesPlugin
AddCubePlugin --> PluginAPI
AddCubePlugin --> CallbackIDs
AddCubePlugin --> CommandIDs
AddCubePlugin --> CallableRegistry
AddCubePlugin --> CallableIDs
AddCubePlugin --> Callback
AddCubePlugin --> FunctionComposer
AddCubePlugin --> Observer
AddCubePlugin --> CommandRegistry
AddCubePlugin --> OperationalParams
AddCubePlugin --> Command
AddCubePlugin --> MaterialRegistry
AddCubePlugin --> Callable

package "AddPlanePlugin" {
    class AddPlaneCommand
    class AddPlaneCallback
    class PlaneVertexGenCallable

    AddPlaneCallback --> PlaneVertexGenCallable
}
AddPlanePlugin --> MeshAdderCallablesPlugin
AddPlanePlugin --> PluginAPI
AddPlanePlugin --> CallbackIDs
AddPlanePlugin --> CommandIDs
AddPlanePlugin --> CallableIDs
AddPlanePlugin --> Callback
AddPlanePlugin --> FunctionComposer
AddPlanePlugin --> Observer
AddPlanePlugin --> OperationalParams
AddPlanePlugin --> Command
AddPlanePlugin --> CallableRegistry
AddPlanePlugin --> MaterialRegistry

package "FetchSurfacePlugin" {
    class FetchSurfaceCommand
    class FetchSurfaceCallback
    class FetchedSurfaceVertexGenCallable

    FetchSurfaceCallback --> FetchedSurfaceVertexGenCallable
}
FetchSurfacePlugin --> MeshAdderCallablesPlugin
FetchSurfacePlugin --> PluginAPI
FetchSurfacePlugin --> CallbackIDs
FetchSurfacePlugin --> CommandIDs
FetchSurfacePlugin --> CallableRegistry
FetchSurfacePlugin --> Callable
FetchSurfacePlugin --> OperationalParams
FetchSurfacePlugin --> CallableIDs
FetchSurfacePlugin --> CallbackRegister
FetchSurfacePlugin --> Callback
FetchSurfacePlugin --> FunctionComposer
FetchSurfacePlugin --> Observer
FetchSurfacePlugin --> CommandRegistry
FetchSurfacePlugin --> TiffGrayscaleMapLoader
    TiffGrayscaleMapLoader --> tiffio
FetchSurfacePlugin --> CurlFileFetcher
    CurlFileFetcher --> curl
FetchSurfacePlugin --> ThirdApiUtils
    ThirdApiUtils --> OperationalParams

class AdditionLayer
AdditionLayer --> AddCubePlugin
AdditionLayer --> AddPlanePlugin
AdditionLayer --> FetchSurfacePlugin
AdditionLayer --> PluginAPI
AdditionLayer --> LayerIDs
AdditionLayer --> CommandRegistry
AdditionLayer --> CommandIDs
AdditionLayer --> Observer
AdditionLayer --> Layer
AdditionLayer --> LayerRegistry
AdditionLayer --> imgui

package "MoveVertexPlugin"{
    class MoveVertexCallBack
    class MoveVertexCommand
}
MoveVertexPlugin --> PluginAPI
MoveVertexPlugin --> CallbackIDs
MoveVertexPlugin --> CommandIDs
MoveVertexPlugin --> CallbackRegister
MoveVertexPlugin --> ViewPortsController
MoveVertexPlugin --> InterpolationUtils
MoveVertexPlugin --> GeometryUtils
MoveVertexPlugin --> MaterialRegistry
MoveVertexPlugin --> OperationalParams
MoveVertexPlugin --> Callback
MoveVertexPlugin --> Observer
MoveVertexPlugin --> CommandRegistry
MoveVertexPlugin --> Command

package "MoveMeshPlugin"{
    class MoveMeshCallBack
    class MoveMeshCommand
}
MoveMeshPlugin --> MoveVertexPlugin
MoveMeshPlugin --> PluginAPI
MoveMeshPlugin --> CallbackIDs
MoveMeshPlugin --> CommandIDs
MoveMeshPlugin --> OperationalParams
MoveMeshPlugin --> Command
MoveMeshPlugin --> Observer
MoveMeshPlugin --> CommandRegistry
MoveMeshPlugin --> Callback
MoveMeshPlugin --> ViewPortsController
MoveMeshPlugin --> InterpolationUtils
MoveMeshPlugin --> GeometryUtils
MoveMeshPlugin --> MaterialRegistry

package "MoveSelectedFacesPlugin"{
    class MoveSelectedFacesCallBack
    class MoveSelectedFacesCommand
}
MoveSelectedFacesPlugin --> MoveVertexPlugin
MoveSelectedFacesPlugin --> PluginAPI
MoveSelectedFacesPlugin --> CallbackIDs
MoveSelectedFacesPlugin --> CommandIDs
MoveSelectedFacesPlugin --> Command
MoveSelectedFacesPlugin --> Observer
MoveSelectedFacesPlugin --> CommandRegistry
MoveSelectedFacesPlugin --> OperationalParams
MoveSelectedFacesPlugin --> Callback
MoveSelectedFacesPlugin --> CallbackRegister
MoveSelectedFacesPlugin --> ViewPortsController
MoveSelectedFacesPlugin --> InterpolationUtils
MoveSelectedFacesPlugin --> GeometryUtils
MoveSelectedFacesPlugin --> MaterialRegistry

package "MoveSelectedMeshesPlugin"{
    class MoveSelectedMeshesCallBack
    class MoveSelectedMeshesCommand
}
MoveSelectedMeshesPlugin --> MoveMeshPlugin
MoveSelectedMeshesPlugin --> PluginAPI
MoveSelectedMeshesPlugin --> CallbackIDs
MoveSelectedMeshesPlugin --> CommandIDs
MoveSelectedMeshesPlugin --> OperationalParams
MoveSelectedMeshesPlugin --> Observer
MoveSelectedMeshesPlugin --> Command
MoveSelectedMeshesPlugin --> CommandRegistry
MoveSelectedMeshesPlugin --> Callback
MoveSelectedMeshesPlugin --> CallbackRegister
MoveSelectedMeshesPlugin --> ViewPortsController
MoveSelectedMeshesPlugin --> InterpolationUtils
MoveSelectedMeshesPlugin --> GeometryUtils
MoveSelectedMeshesPlugin --> MaterialRegistry

package "BrushToolPlugin" {
    class BrushToolCommand
    class BrushToolCallBack
    class BrushTool
    class BrushInteractionHandler

    BrushTool --> BrushInteractionHandler
}
BrushToolPlugin --> MoveVertexPlugin
BrushToolPlugin --> PluginAPI
BrushToolPlugin --> CommandIDs
BrushToolPlugin --> ToolIDs
BrushToolPlugin --> CallbackIDs
BrushToolPlugin --> Observer
BrushToolPlugin --> Command
BrushToolPlugin --> Octree
BrushToolPlugin --> CommandRegistry
BrushToolPlugin --> OperationalParams
BrushToolPlugin --> Callback
BrushToolPlugin --> CallbackRegister
BrushToolPlugin --> InterpolationUtils
BrushToolPlugin --> GeometryUtils
BrushToolPlugin --> ViewPortsController
BrushToolPlugin --> Tool
BrushToolPlugin --> ToolRegistry
BrushToolPlugin --> InteractionHandler

class SculptToolLayer
SculptToolLayer --> BrushToolPlugin
SculptToolLayer --> PluginAPI
SculptToolLayer --> LayerIDs
SculptToolLayer --> Layer
SculptToolLayer --> LayerRegistry
SculptToolLayer --> Observer
SculptToolLayer --> ViewPortsController
SculptToolLayer --> imgui
SculptToolLayer --> ToolIDs
SculptToolLayer --> ToolRegistry

package "CreatePrintPlugin" {
    class CreatePrintStructureCallBack
    class CreatePrintCommand
}
CreatePrintPlugin --> AddNodesToOutlinerLayerPlugin
CreatePrintPlugin --> PluginAPI
CreatePrintPlugin --> CommandIDs
CreatePrintPlugin --> CallbackIDs
CreatePrintPlugin --> Callback
CreatePrintPlugin --> OperationalParams
CreatePrintPlugin --> Observer
CreatePrintPlugin --> CallbackRegister
CreatePrintPlugin --> PrintableMesh
CreatePrintPlugin --> Renderer
    Renderer --> Buffers
    Renderer --> PrintableMesh
    Renderer --> BufferStorageData
    Renderer --> ViewPortsController
CreatePrintPlugin --> Scene
CreatePrintPlugin --> GeometryUtils
CreatePrintPlugin --> glm
CreatePrintPlugin --> ViewPortsController
CreatePrintPlugin --> MaterialRegistry
CreatePrintPlugin --> Command

class PrintableMeshSettingsPopUpLayer
PrintableMeshSettingsPopUpLayer --> CreatePrintPlugin
PrintableMeshSettingsPopUpLayer --> PluginAPI
PrintableMeshSettingsPopUpLayer --> LayerIDs
PrintableMeshSettingsPopUpLayer --> Layer
PrintableMeshSettingsPopUpLayer --> LayerRegistry
PrintableMeshSettingsPopUpLayer --> Observer
PrintableMeshSettingsPopUpLayer --> WindowLayerBus
PrintableMeshSettingsPopUpLayer --> CommandRegistry
PrintableMeshSettingsPopUpLayer --> CommandIDs
PrintableMeshSettingsPopUpLayer --> imgui

package "DeleteFacePlugin"{
    class DeleteFaceCallBack
    class DeleteFaceCommand
}
DeleteFacePlugin --> PluginAPI
DeleteFacePlugin --> CommandIDs
DeleteFacePlugin --> CallbackIDs
DeleteFacePlugin --> Command
DeleteFacePlugin --> Observer
DeleteFacePlugin --> CommandRegistry
DeleteFacePlugin --> Callback
DeleteFacePlugin --> OperationalParams
DeleteFacePlugin --> CallbackRegister
DeleteFacePlugin --> ContainerUtils
DeleteFacePlugin --> ExtendedHalfEdge
DeleteFacePlugin --> ViewPortsController
DeleteFacePlugin --> MaterialRegistry

package "DeleteMeshPlugin"{
    class DeleteMeshCallBack
    class DeleteMeshCommand
 }
 DeleteMeshPlugin --> PluginAPI
 DeleteMeshPlugin --> CommandIDs
 DeleteMeshPlugin --> CallbackIDs
 DeleteMeshPlugin --> Command
 DeleteMeshPlugin --> Observer
 DeleteMeshPlugin --> CommandRegistry
 DeleteMeshPlugin --> Callback
 DeleteMeshPlugin --> OperationalParams
 DeleteMeshPlugin --> CallbackRegister
 DeleteMeshPlugin --> ExtendedHalfEdge

package "DeleteSelectedFacesPlugin" {
    class DeleteSelectedFacesCallBack
    class DeleteSelectedFacesCommand
}
DeleteSelectedFacesPlugin --> DeleteFacePlugin
DeleteSelectedFacesPlugin --> PluginAPI
DeleteSelectedFacesPlugin --> CommandIDs
DeleteSelectedFacesPlugin --> CallbackIDs
DeleteSelectedFacesPlugin --> Command
DeleteSelectedFacesPlugin --> Observer
DeleteSelectedFacesPlugin --> CommandRegistry
DeleteSelectedFacesPlugin --> OperationalParams
DeleteSelectedFacesPlugin --> Callback
DeleteSelectedFacesPlugin --> CallbackRegister
DeleteSelectedFacesPlugin --> ContainerUtils
DeleteSelectedFacesPlugin --> ExtendedHalfEdge
DeleteSelectedFacesPlugin --> ViewPortsController

package "DeleteSelectedMeshesPlugin" {
    class DeleteSelectedMeshesCallBack
    class DeleteSelectedMeshesCommand
}
DeleteSelectedMeshesPlugin --> DeleteMeshPlugin
DeleteSelectedMeshesPlugin --> PluginAPI
DeleteSelectedMeshesPlugin --> CommandIDs
DeleteSelectedMeshesPlugin --> CallbackIDs
DeleteSelectedMeshesPlugin --> Command
DeleteSelectedMeshesPlugin --> Observer
DeleteSelectedMeshesPlugin --> CommandRegistry
DeleteSelectedMeshesPlugin --> Callback
DeleteSelectedMeshesPlugin --> ViewPortsController
DeleteSelectedMeshesPlugin --> CallbackRegister

class RemovalLayer
RemovalLayer --> DeleteSelectedFacesPlugin
RemovalLayer --> DeleteSelectedMeshesPlugin
RemovalLayer --> PluginAPI
RemovalLayer --> LayerIDs
RemovalLayer --> Layer
RemovalLayer --> Observer
RemovalLayer --> LayerRegistry
RemovalLayer --> CommandIDs
RemovalLayer --> CommandRegistry
RemovalLayer --> imgui

package "SelectFacePlugin"{
    class SelectFaceCallBack
    class SelectFaceCommand
    class FaceSelectionTool
}
SelectFacePlugin --> PluginAPI
SelectFacePlugin --> CommandIDs
SelectFacePlugin --> ToolIDs
SelectFacePlugin --> CallbackIDs
SelectFacePlugin --> Command
SelectFacePlugin --> Observer
SelectFacePlugin --> CommandRegistry
SelectFacePlugin --> Callback
SelectFacePlugin --> CallbackRegister
SelectFacePlugin --> ViewPortsController
SelectFacePlugin --> SelectionHandler
    SelectionHandler --> InteractionHandler
    SelectionHandler --> CommandRegistry
SelectFacePlugin --> Tool
SelectFacePlugin --> ToolRegistry

package "DeselectFacePlugin"{
    class DeslectFaceCallBack
    class DeslectFaceCommand
    class FaceDeselectionTool
}
DeselectFacePlugin --> PluginAPI
DeselectFacePlugin --> ToolIDs
DeselectFacePlugin --> CommandIDs
DeselectFacePlugin --> CallbackIDs
DeselectFacePlugin --> DeselectionHandler
    DeselectionHandler --> InteractionHandler
DeselectFacePlugin --> Command
DeselectFacePlugin --> Tool
DeselectFacePlugin --> ToolRegistry
DeselectFacePlugin --> Observer
DeselectFacePlugin --> CommandRegistry
DeselectFacePlugin --> Callback
DeselectFacePlugin --> CallbackRegister
DeselectFacePlugin --> FaceSelectionManager
DeselectFacePlugin --> ViewPortsController
DeselectFacePlugin --> Scene

package "SelectMeshPlugin"{
    class SelectMeshCallBack
    class SelectMeshCommand
    class MeshSelectionTool
}
SelectMeshPlugin --> PluginAPI
SelectMeshPlugin --> ToolIDs
SelectMeshPlugin --> CommandIDs
SelectMeshPlugin --> CallbackIDs
SelectMeshPlugin --> Command
SelectMeshPlugin --> Observer
SelectMeshPlugin --> CommandRegistry
SelectMeshPlugin --> Callback
SelectMeshPlugin --> CallbackRegister
SelectMeshPlugin --> ViewPortsController
SelectMeshPlugin --> Tool
SelectMeshPlugin --> SelectionHandler
SelectMeshPlugin --> ToolRegistry

package "DeselectMeshPlugin"{
    class DeslectMeshCallBack
    class DeslectMeshCommand
    class MeshDeselectionTool
}
DeselectMeshPlugin --> PluginAPI
DeselectMeshPlugin --> ToolIDs
DeselectMeshPlugin --> CallbackIDs
DeselectMeshPlugin --> CommandIDs
DeselectMeshPlugin --> Tool
DeselectMeshPlugin --> Observer
DeselectMeshPlugin --> ToolRegistry
DeselectMeshPlugin --> DeselectionHandler
DeselectMeshPlugin --> Command
DeselectMeshPlugin --> CommandRegistry
DeselectMeshPlugin --> CallbackRegister
DeselectMeshPlugin --> Callback
DeselectMeshPlugin --> ViewPortsController

package "SelectionLayerPlugin"{
    class SelectionLayer
    class SelectionLayerCallback
}
SelectionLayerPlugin--> SelectFacePlugin
SelectionLayerPlugin --> DeselectFacePlugin
SelectionLayerPlugin --> SelectMeshPlugin
SelectionLayerPlugin --> DeselectMeshPlugin
SelectionLayerPlugin --> PluginAPI
SelectionLayerPlugin --> LayerIDs
SelectionLayerPlugin --> LayerRegistry
SelectionLayerPlugin --> CallableIDs
SelectionLayerPlugin --> CallbackRegister
SelectionLayerPlugin --> Application
SelectionLayerPlugin --> ViewPortsController
SelectionLayerPlugin --> Callback
SelectionLayerPlugin --> Observer
SelectionLayerPlugin --> OperationalParams
SelectionLayerPlugin --> ToolIDs
SelectionLayerPlugin --> ToolRegistry
SelectionLayerPlugin --> Layer
SelectionLayerPlugin --> imgui

package "HandleGizmoPlugin"{
    class HandleGizmoCommand
    class HandleGizmoCallback
}
HandleGizmoPlugin --> MoveSelectedMeshesPlugin
HandleGizmoPlugin --> MoveSelectedFacesPlugin
HandleGizmoPlugin --> PluginAPI
HandleGizmoPlugin --> CallbackIDs
HandleGizmoPlugin --> CommandIDs
HandleGizmoPlugin --> OperationalParams
HandleGizmoPlugin --> Command
HandleGizmoPlugin --> Observer
HandleGizmoPlugin --> CommandRegistry
HandleGizmoPlugin --> Callback
HandleGizmoPlugin --> CallbackRegister
HandleGizmoPlugin --> ImGuizmo
HandleGizmoPlugin --> ViewPortsController

class GizmoLayer
GizmoLayer --> HandleGizmoPlugin
GizmoLayer --> PluginAPI
GizmoLayer --> LayerIDs
GizmoLayer --> Layer
GizmoLayer --> LayerRegistry
GizmoLayer --> Observer
GizmoLayer --> ImGuizmo
GizmoLayer --> ViewPortsController
GizmoLayer --> CommandRegistry
GizmoLayer --> CommandIDs

package "SolidifyMeshesPlugin" {
    class SolidifyMeshesCallBack
    class SolidifyMeshesCommand
    class EdgesVaoInitCallable
    class FaceVaoInitCallable
    class SceneFacesAdderCallable

    class FacesVaoInitCallable

    SolidifyMeshesCallBack --> ConnectEdgesCallBack
    SolidifyMeshesCallBack --> EdgesVaoInitCallable
    SolidifyMeshesCallBack --> FaceVaoInitCallable
    SolidifyMeshesCallBack --> SceneFacesAdderCallable
    SolidifyMeshesCallBack --> FacesVaoInitCallable
}

SolidifyMeshesPlugin --> PluginAPI
SolidifyMeshesPlugin --> CommandIDs
SolidifyMeshesPlugin --> CallbackIDs
SolidifyMeshesPlugin --> Command
SolidifyMeshesPlugin --> Observer
SolidifyMeshesPlugin --> CommandRegistry
SolidifyMeshesPlugin --> Callback
SolidifyMeshesPlugin --> OperationalParams
SolidifyMeshesPlugin --> CallbackRegister
SolidifyMeshesPlugin --> CallableIDs
SolidifyMeshesPlugin --> CallableRegistry
SolidifyMeshesPlugin --> SelectionController
SolidifyMeshesPlugin --> Renderer
SolidifyMeshesPlugin --> Scene
SolidifyMeshesPlugin --> GeometryUtils
SolidifyMeshesPlugin --> glm
SolidifyMeshesPlugin --> ViewPortsController
SolidifyMeshesPlugin --> Octree

class ModifiersLayer
ModifiersLayer --> CreatePrintPlugin
ModifiersLayer --> SolidifyMeshesPlugin
ModifiersLayer --> PluginAPI
ModifiersLayer --> LayerIDs
ModifiersLayer --> Layer
ModifiersLayer --> LayerRegistry
ModifiersLayer --> Observer
ModifiersLayer --> WindowLayerBus
ModifiersLayer --> CommandIDs
ModifiersLayer --> CommandRegistry
ModifiersLayer --> imgui

package "ImportMeshesPlugin" {
    class ImportMeshesCommand
    class ImportMeshesCallBack
}
ImportMeshesPlugin --> PluginAPI
ImportMeshesPlugin --> CallbackIDs
ImportMeshesPlugin --> CommandIDs
ImportMeshesPlugin --> Command
ImportMeshesPlugin --> CommandRegistry
ImportMeshesPlugin --> Callback
ImportMeshesPlugin --> CallbackRegister
ImportMeshesPlugin --> Observer
ImportMeshesPlugin --> OperationalParams
ImportMeshesPlugin --> ViewPortsController
ImportMeshesPlugin --> OBJImporter
    OBJImporter --> BaseImporter
        BaseImporter --> Mesh

package "ExportMeshesPlugin" {
    class ExportMeshesCommand
    class ExportMeshesCallBack
}
ExportMeshesPlugin --> PluginAPI
ExportMeshesPlugin --> CallbackIDs
ExportMeshesPlugin --> CommandIDs
ExportMeshesPlugin --> Command
ExportMeshesPlugin --> CommandRegistry
ExportMeshesPlugin --> Observer
ExportMeshesPlugin --> Callback
ExportMeshesPlugin --> CallbackRegister
ExportMeshesPlugin --> OperationalParams
ExportMeshesPlugin --> OBJExporter
    OBJExporter --> BaseExporter
        BaseExporter --> Mesh

class ImportExportLayer
ImportExportLayer --> ImportMeshesPlugin
ImportExportLayer --> ExportMeshesPlugin
ImportExportLayer --> PluginAPI
ImportExportLayer --> LayerIDs
ImportExportLayer --> Layer
ImportExportLayer --> LayerRegistry
ImportExportLayer --> Observer
ImportExportLayer --> CommandRegistry
ImportExportLayer --> CommandIDs
ImportExportLayer --> imgui

