#pragma once

enum CommandIDS {
    ADD_CUBE_COMMAND = 0,
    ADD_PLANE_COMMAND,
    BASIC_SCULPT_TOOL_COMMAND,
    BRUSH_TOOL_COMMAND,
    CREATE_PRINT_COMMAND,
    DELETE_FACE_COMMAND,
    DELETE_MESH_COMMAND,
    DELETE_SELECTED_FACES_COMMAND,
    DELETE_SELECTED_MESHES_COMMAND,
    DESELECT_FACE_COMMAND,
    DESELECT_MESH_COMMAND,
    EXPORT_MESHES_COMMAND,
    FETCH_SURFACE_COMMAND,
    IMPORT_MESHES_COMMAND,
    MOVE_FACE_COMMAND,
    MOVE_SELECTED_FACE_COMMAND,
    MOVE_VERTEX_COMMAND,
    SELECT_FACE_COMMAND,
    SELECT_MESH_COMMAND,
    SOLIDIFY_MESHES_COMMAND
};
