#pragma once

#define ADD_CUBE_COMMAND 0
#define ADD_PLANE_COMMAND 1
#define BASIC_SCULPT_TOOL_COMMAND 2
#define BRUSH_TOOL_COMMAND 3
#define CREATE_PRINT_COMMAND 4
#define DELETE_FACE_COMMAND 5
#define DELETE_MESH_COMMAND 6
#define DELETE_SELECTED_FACES_COMMAND 7
#define DELETE_SELECTED_MESHES_COMMAND 8
#define DESELECT_FACE_COMMAND 9
#define DESELECT_MESH_COMMAND 10
#define EXPORT_MESHES_COMMAND 11
#define FETCH_SURFACE_COMMAND 12
#define IMPORT_MESHES_COMMAND 13
#define MOVE_FACE_COMMAND 14
#define MOVE_SELECTED_FACE_COMMAND 15
#define MOVE_VERTEX_COMMAND 16
#define SELECT_FACE_COMMAND 17
#define SELECT_MESH_COMMAND 18
#define SOLIDIFY_MESHES_COMMAND 19