@startuml OutlinerLayerDependencies

package AddNodesToOutlinerLayerPlugin {
    class AddNewOutlinerNodeCallBack
    class AddChildOutlinerNodeCallBack
}

class OutlinerLayer
AddNodesToOutlinerLayerPlugin -[thickness=3]-> OutlinerLayer

@enduml